stages:
  create_experiment:
    cmd: python src/create_experiment.py
    deps:
      - src/create_experiment.py
    outs:
      - experiments/experiment.yaml
  preprocess:
    cmd: python src/preprocess.py
    deps:
      - src/preprocess.py
      - params.yaml
    outs:
      - data/X_train.pkl
      - data/X_test.pkl
      - data/y_train.pkl
      - data/y_test.pkl
  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/X_train.pkl
      - data/X_test.pkl
      - data/y_train.pkl
      - data/y_test.pkl
      - params.yaml
  predict:
    cmd: python src/predict.py
    deps:
      - src/predict.py
      - model/logreg_model.pkl
      - data/X_test.pkl
      - data/y_test.pkl
      - params.yaml

