preprocess:
  test_size: 0.2
  random_state: 42
  normalize: true

train:
  model_type: sgd
  loss: log_loss
  max_iter: 50
  tol: 0.001
  random_state: 42


predict:
  num_samples: 10
  random_seed: 123
